package com.hardik.seaminaction.model;
// Generated Sep 7, 2009 10:56:32 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", schema = "public")
public class Course implements java.io.Serializable {

	private long id;
	private Facility facility;
	private String name;
	private String description;
	private String designer;
	private String fairways;
	private String greens;
	private Integer yearBuilt;
	private int numHoles;
	private Long signatureHole;
	private Set<TeeSet> teeSets = new HashSet<TeeSet>(0);
	private Set<TeeSet> teeSets_1 = new HashSet<TeeSet>(0);
	private Set<Hole> holes = new HashSet<Hole>(0);
	private Set<Hole> holes_1 = new HashSet<Hole>(0);

	public Course() {
	}

	public Course(long id, Facility facility, String fairways, String greens,
			int numHoles) {
		this.id = id;
		this.facility = facility;
		this.fairways = fairways;
		this.greens = greens;
		this.numHoles = numHoles;
	}
	public Course(long id, Facility facility, String name, String description,
			String designer, String fairways, String greens, Integer yearBuilt,
			int numHoles, Long signatureHole, Set<TeeSet> teeSets,
			Set<TeeSet> teeSets_1, Set<Hole> holes, Set<Hole> holes_1) {
		this.id = id;
		this.facility = facility;
		this.name = name;
		this.description = description;
		this.designer = designer;
		this.fairways = fairways;
		this.greens = greens;
		this.yearBuilt = yearBuilt;
		this.numHoles = numHoles;
		this.signatureHole = signatureHole;
		this.teeSets = teeSets;
		this.teeSets_1 = teeSets_1;
		this.holes = holes;
		this.holes_1 = holes_1;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "facility_id", nullable = false)
	@NotNull
	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	@Column(name = "name", length = 50)
	@Length(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	@Length(max = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "designer", length = 50)
	@Length(max = 50)
	public String getDesigner() {
		return this.designer;
	}

	public void setDesigner(String designer) {
		this.designer = designer;
	}

	@Column(name = "fairways", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getFairways() {
		return this.fairways;
	}

	public void setFairways(String fairways) {
		this.fairways = fairways;
	}

	@Column(name = "greens", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getGreens() {
		return this.greens;
	}

	public void setGreens(String greens) {
		this.greens = greens;
	}

	@Column(name = "year_built")
	public Integer getYearBuilt() {
		return this.yearBuilt;
	}

	public void setYearBuilt(Integer yearBuilt) {
		this.yearBuilt = yearBuilt;
	}

	@Column(name = "num_holes", nullable = false)
	public int getNumHoles() {
		return this.numHoles;
	}

	public void setNumHoles(int numHoles) {
		this.numHoles = numHoles;
	}

	@Column(name = "signature_hole")
	public Long getSignatureHole() {
		return this.signatureHole;
	}

	public void setSignatureHole(Long signatureHole) {
		this.signatureHole = signatureHole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<TeeSet> getTeeSets() {
		return this.teeSets;
	}

	public void setTeeSets(Set<TeeSet> teeSets) {
		this.teeSets = teeSets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<TeeSet> getTeeSets_1() {
		return this.teeSets_1;
	}

	public void setTeeSets_1(Set<TeeSet> teeSets_1) {
		this.teeSets_1 = teeSets_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Hole> getHoles() {
		return this.holes;
	}

	public void setHoles(Set<Hole> holes) {
		this.holes = holes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Hole> getHoles_1() {
		return this.holes_1;
	}

	public void setHoles_1(Set<Hole> holes_1) {
		this.holes_1 = holes_1;
	}

}
