package com.hardik.seaminaction.model;
// Generated Sep 7, 2009 10:56:32 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Facility generated by hbm2java
 */
@Entity
@Table(name = "facility", schema = "public")
public class Facility implements java.io.Serializable {

	private long id;
	private String name;
	private String description;
	private String type;
	private String address;
	private String city;
	private String state;
	private String zip;
	private String county;
	private String country;
	private String phone;
	private String uri;
	private Integer priceRange;
	private Set<Course> courses = new HashSet<Course>(0);
	private Set<Course> courses_1 = new HashSet<Course>(0);

	public Facility() {
	}

	public Facility(long id, String name, String type) {
		this.id = id;
		this.name = name;
		this.type = type;
	}
	public Facility(long id, String name, String description, String type,
			String address, String city, String state, String zip,
			String county, String country, String phone, String uri,
			Integer priceRange, Set<Course> courses, Set<Course> courses_1) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.type = type;
		this.address = address;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.county = county;
		this.country = country;
		this.phone = phone;
		this.uri = uri;
		this.priceRange = priceRange;
		this.courses = courses;
		this.courses_1 = courses_1;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	@Length(max = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "address", length = 50)
	@Length(max = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city", length = 30)
	@Length(max = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 2)
	@Length(max = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zip", length = 5)
	@Length(max = 5)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "county", length = 30)
	@Length(max = 30)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "country", length = 30)
	@Length(max = 30)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "phone", length = 10)
	@Length(max = 10)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "uri")
	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	@Column(name = "price_range")
	public Integer getPriceRange() {
		return this.priceRange;
	}

	public void setPriceRange(Integer priceRange) {
		this.priceRange = priceRange;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facility")
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facility")
	public Set<Course> getCourses_1() {
		return this.courses_1;
	}

	public void setCourses_1(Set<Course> courses_1) {
		this.courses_1 = courses_1;
	}

}
