package com.hardik.seaminaction.model;
// Generated Sep 7, 2009 10:56:32 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Hole generated by hbm2java
 */
@Entity
@Table(name = "hole", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"number", "course_id"}))
public class Hole implements java.io.Serializable {

	private long id;
	private Course course;
	private String name;
	private int number;
	private int MPar;
	private Integer MHandicap;
	private int LPar;
	private Integer LHandicap;
	private Set<Tee> tees = new HashSet<Tee>(0);
	private Set<Tee> tees_1 = new HashSet<Tee>(0);

	public Hole() {
	}

	public Hole(long id, Course course, int number, int MPar, int LPar) {
		this.id = id;
		this.course = course;
		this.number = number;
		this.MPar = MPar;
		this.LPar = LPar;
	}
	public Hole(long id, Course course, String name, int number, int MPar,
			Integer MHandicap, int LPar, Integer LHandicap, Set<Tee> tees,
			Set<Tee> tees_1) {
		this.id = id;
		this.course = course;
		this.name = name;
		this.number = number;
		this.MPar = MPar;
		this.MHandicap = MHandicap;
		this.LPar = LPar;
		this.LHandicap = LHandicap;
		this.tees = tees;
		this.tees_1 = tees_1;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id", nullable = false)
	@NotNull
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "name", length = 25)
	@Length(max = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "number", nullable = false)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	@Column(name = "m_par", nullable = false)
	public int getMPar() {
		return this.MPar;
	}

	public void setMPar(int MPar) {
		this.MPar = MPar;
	}

	@Column(name = "m_handicap")
	public Integer getMHandicap() {
		return this.MHandicap;
	}

	public void setMHandicap(Integer MHandicap) {
		this.MHandicap = MHandicap;
	}

	@Column(name = "l_par", nullable = false)
	public int getLPar() {
		return this.LPar;
	}

	public void setLPar(int LPar) {
		this.LPar = LPar;
	}

	@Column(name = "l_handicap")
	public Integer getLHandicap() {
		return this.LHandicap;
	}

	public void setLHandicap(Integer LHandicap) {
		this.LHandicap = LHandicap;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hole")
	public Set<Tee> getTees() {
		return this.tees;
	}

	public void setTees(Set<Tee> tees) {
		this.tees = tees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hole")
	public Set<Tee> getTees_1() {
		return this.tees_1;
	}

	public void setTees_1(Set<Tee> tees_1) {
		this.tees_1 = tees_1;
	}

}
