package com.hardik.seaminaction.model;
// Generated Sep 7, 2009 10:56:32 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TeeId generated by hbm2java
 */
@Embeddable
public class TeeId implements java.io.Serializable {

	private long teeSetId;
	private long holeId;

	public TeeId() {
	}

	public TeeId(long teeSetId, long holeId) {
		this.teeSetId = teeSetId;
		this.holeId = holeId;
	}

	@Column(name = "tee_set_id", nullable = false)
	public long getTeeSetId() {
		return this.teeSetId;
	}

	public void setTeeSetId(long teeSetId) {
		this.teeSetId = teeSetId;
	}

	@Column(name = "hole_id", nullable = false)
	public long getHoleId() {
		return this.holeId;
	}

	public void setHoleId(long holeId) {
		this.holeId = holeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TeeId))
			return false;
		TeeId castOther = (TeeId) other;

		return (this.getTeeSetId() == castOther.getTeeSetId())
				&& (this.getHoleId() == castOther.getHoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getTeeSetId();
		result = 37 * result + (int) this.getHoleId();
		return result;
	}

}
