package com.hardik.seaminaction.model;
// Generated Sep 7, 2009 10:56:32 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TeeSet generated by hbm2java
 */
@Entity
@Table(name = "tee_set", schema = "public", uniqueConstraints = {
		@UniqueConstraint(columnNames = {"color", "course_id"}),
		@UniqueConstraint(columnNames = {"pos", "course_id"})})
public class TeeSet implements java.io.Serializable {

	private long id;
	private Course course;
	private String name;
	private String color;
	private Double LCourseRating;
	private Double LSlopeRating;
	private Double MCourseRating;
	private Double MSlopeRating;
	private Integer pos;
	private Set<Tee> tees = new HashSet<Tee>(0);
	private Set<Tee> tees_1 = new HashSet<Tee>(0);

	public TeeSet() {
	}

	public TeeSet(long id, Course course, String color) {
		this.id = id;
		this.course = course;
		this.color = color;
	}
	public TeeSet(long id, Course course, String name, String color,
			Double LCourseRating, Double LSlopeRating, Double MCourseRating,
			Double MSlopeRating, Integer pos, Set<Tee> tees, Set<Tee> tees_1) {
		this.id = id;
		this.course = course;
		this.name = name;
		this.color = color;
		this.LCourseRating = LCourseRating;
		this.LSlopeRating = LSlopeRating;
		this.MCourseRating = MCourseRating;
		this.MSlopeRating = MSlopeRating;
		this.pos = pos;
		this.tees = tees;
		this.tees_1 = tees_1;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id", nullable = false)
	@NotNull
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "name", length = 25)
	@Length(max = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "color", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "l_course_rating", precision = 17, scale = 17)
	public Double getLCourseRating() {
		return this.LCourseRating;
	}

	public void setLCourseRating(Double LCourseRating) {
		this.LCourseRating = LCourseRating;
	}

	@Column(name = "l_slope_rating", precision = 17, scale = 17)
	public Double getLSlopeRating() {
		return this.LSlopeRating;
	}

	public void setLSlopeRating(Double LSlopeRating) {
		this.LSlopeRating = LSlopeRating;
	}

	@Column(name = "m_course_rating", precision = 17, scale = 17)
	public Double getMCourseRating() {
		return this.MCourseRating;
	}

	public void setMCourseRating(Double MCourseRating) {
		this.MCourseRating = MCourseRating;
	}

	@Column(name = "m_slope_rating", precision = 17, scale = 17)
	public Double getMSlopeRating() {
		return this.MSlopeRating;
	}

	public void setMSlopeRating(Double MSlopeRating) {
		this.MSlopeRating = MSlopeRating;
	}

	@Column(name = "pos")
	public Integer getPos() {
		return this.pos;
	}

	public void setPos(Integer pos) {
		this.pos = pos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teeSet")
	public Set<Tee> getTees() {
		return this.tees;
	}

	public void setTees(Set<Tee> tees) {
		this.tees = tees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teeSet")
	public Set<Tee> getTees_1() {
		return this.tees_1;
	}

	public void setTees_1(Set<Tee> tees_1) {
		this.tees_1 = tees_1;
	}

}
